#!/bin/sh

out=./lib/meta.js
rm -f $out

echo "// Autogenerated file, don't change by hand" >> $out
echo "// Run build-meta.sh from project root to regenerate this file\n" >> $out

echo "module.exports = {\n" >> $out

for file in ./meta/*.json
do
    content=`sed "s@\"@\\\\\\\\\\"@g" $file`

    echo \"`basename $file '.json'`\": \"$content\", >> ./lib/meta.js
done

echo "\"_\": \"hack to fix last comma in the object\" };" >> $out
