#!/bin/sh

out=./lib/hl7grok.js
rm -f $out

echo "// Autogenerated file, don't change by hand" >> $out
echo "// Run build.sh from hl7grok root to rebuild this file\n" >> $out

echo "(function () {" >> $out
echo "var HL7_META = {\n" >> $out

for file in ./meta/*.json
do
    echo \"`basename $file '.json'`\": >> $out
    cat $file | python -c 'import json,sys; obj=json.load(sys.stdin); print json.dumps(json.dumps(obj))' >> $out
    echo , >> $out
done

echo "\"_\": \"hack to fix last comma in the object\" };" >> $out

cat ./src/hl7grok.coffee | coffee -c -s -b >> $out

echo "}).call(this);" >> $out
