#!/bin/bash

out=./lib/hl7grok.js
rm -f $out

meta/build-meta.js

echo "// Autogenerated file, don't change by hand" >> $out
echo "// Run build.sh from hl7grok root to rebuild this file" >> $out

echo '' >> $out

echo "// LZString library by pieroxy" >> $out
echo "// https://github.com/pieroxy/lz-string" >> $out
cat node_modules/lz-string/libs/lz-string.min.js >> $out

echo '' >> $out

echo "(function () {" >> $out
echo -n 'var HL7_META_BASE64 = "' >> $out
cat meta/meta.base64 >> $out
echo -n '";' >> $out

cat ./src/hl7grok.js >> $out

echo "}).call(this);" >> $out
